const test=require('node:test'),assert=require('node:assert/strict'),P=require('../pesten/engine.js');
const c=(r,s=0)=>r*4+s;
function setup(hand,top=c(3),extras={}){return {hands:[hand,[c(4,1),c(5,1)],[c(8,2),c(9,2)],[c(11,3),c(12,3)]],deck:[c(2,1),c(3,1),c(4,2),c(5,2)],discard:[top],activeSuit:P.suit(top),turn:0,direction:1,pending:0,penalty:null,drawn:null,winner:null,plays:0,...extras};}
test('deal: 54 unique cards, 7 per player and harmless starting discard',()=>{const s=P.create(()=>.4);assert.equal(s.hands[0].length,7);assert.equal(s.deck.length,25);assert.equal(new Set([...s.hands.flat(),...s.deck,...s.discard]).size,54);assert([2,3,4,5,8,9,11,12].includes(P.rank(s.discard[0])));});
test('suit/rank matching and wild cards respect active suit',()=>{const ctx=P.context(setup([c(3,1)]));assert(P.canPlay(ctx,c(3,1)));assert(P.canPlay(ctx,c(5)));assert(!P.canPlay(ctx,c(5,1)));assert(P.canPlay(ctx,c(10,1)));assert(P.canPlay(ctx,52));const wild={...ctx,top:c(10),activeSuit:2};assert(!P.canPlay(wild,c(10,1)));assert(P.canPlay(wild,c(3,2)));assert(!P.canPlay(wild,c(3,1)));assert(!P.canPlay(ctx,54));});
test('seven retains turn, eight skips, ace reverses',()=>{for(const [r,turn,dir] of [[6,0,1],[7,2,1],[0,3,-1]]){const s=setup([c(r),c(5)]);P.play(s,c(r),{announced:true});assert.equal(s.turn,turn);assert.equal(s.direction,dir);assert.equal(s.drawn,null);}});
test('twos and jokers stack separately; penalty draw ends turn',()=>{const s=setup([c(1),c(5)]);P.play(s,c(1),{announced:true});assert.equal(s.pending,2);assert(!P.canPlay(P.context(s),52));s.hands[1]=[c(1,1),c(4,1)];P.play(s,c(1,1),{announced:true});assert.equal(s.pending,4);const actor=s.turn,result=P.draw(s);assert.equal(result.cards.length,4);assert.equal(s.turn,(actor+1)%4);assert.equal(s.pending,0);const j=setup([52,c(5)]);P.play(j,52,{chosenSuit:3,announced:true});assert.equal(j.pending,5);assert(!P.canPlay(P.context(j),c(1)));j.hands[1]=[53,c(4,1)];P.play(j,53,{chosenSuit:2,announced:true});assert.equal(j.pending,10);assert.equal(j.activeSuit,2);});
test('suit selection is mandatory and invalid plays leave state unchanged',()=>{const s=setup([c(10),c(5)]);const before=JSON.stringify(s);for(const chosenSuit of [null,-1,4,1.5])assert.throws(()=>P.play(s,c(10),{chosenSuit}));assert.equal(JSON.stringify(s),before);P.play(s,c(10),{chosenSuit:1,announced:true});assert.equal(s.activeSuit,1);assert.equal(s.turn,1);});
test('draw once, play only drawn card, or pass; no premature pass',()=>{const s=setup([c(3,1),c(5)],c(3),{deck:[c(8)]});assert.throws(()=>P.pass(s));P.draw(s);assert.equal(s.drawn,c(8));assert(P.canPlay(P.context(s),c(8)));assert(!P.canPlay(P.context(s),c(5)));assert.throws(()=>P.draw(s));assert.throws(()=>P.play(s,c(5)));P.play(s,c(8));assert.equal(s.turn,1);const x=setup([c(5)],c(3),{deck:[c(8,1)]});P.draw(x);P.pass(x);assert.equal(x.turn,1);assert.equal(x.drawn,null);});
test('forgotten last card draws two; announcement avoids penalty',()=>{const a=setup([c(3,1),c(5)]);const e=P.play(a,c(3,1));assert(e.forgot);assert.equal(a.hands[0].length,3);const b=setup([c(3,1),c(5)]);assert(!P.play(b,c(3,1),{announced:true}).forgot);assert.equal(b.hands[0].length,1);});
test('recycling preserves top discard and exhausted deck remains playable',()=>{const s=setup([c(5)],c(3),{deck:[],discard:[c(8,1),c(9,1),c(3)]});P.draw(s,()=>.5);assert.equal(s.discard.length,1);assert.equal(s.discard[0],c(3));assert.equal(s.deck.length,1);const x=setup([c(5)],c(3),{deck:[]});assert.equal(P.draw(x).cards.length,0);assert.equal(x.drawn,-1);P.pass(x);assert.equal(x.turn,1);});
test('all special cards can finish and ended rounds reject actions',()=>{for(const card of [c(0),c(1),c(6),c(7),c(10),52]){const s=setup([card]);P.play(s,card,{chosenSuit:1});assert.equal(s.winner,0);assert.equal(s.pending,0);assert.throws(()=>P.draw(s));assert.throws(()=>P.pass(s));assert.throws(()=>P.play(s,card));}});
test('600 seeded AI rounds conserve all cards and finish',()=>{let seed=17;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);for(let g=0;g<600;g++){const s=P.create(random);let steps=0;while(s.winner===null&&steps++<2000){const choice=P.choose(s.hands[s.turn],P.context(s),['easy','normal','hard'][g%3],random);if(choice)P.play(s,choice.card,choice);else if(s.drawn!==null)P.pass(s);else P.draw(s,random);const all=[...s.hands.flat(),...s.deck,...s.discard];assert.equal(all.length,54);assert.equal(new Set(all).size,54);}assert.notEqual(s.winner,null,`round ${g} stalled`);assert.equal(s.hands[s.winner].length,0);}});
