(function(){
  'use strict';
  const B=BigTwo,$=id=>document.getElementById(id),names=['Jij','Mei','Kai','Bao'],avatars=['🙂','🦊','🐼','🐯'];
  let state=null,selected=new Set(),timer=null,roundLevel='normal',bySuit=false,sound=false,audio=null,recorded=false,history=[];
  let profile={xp:0,wins:0,games:0,streak:0,best:0,expert:false};
  try{const p=JSON.parse(localStorage.getItem('bigTwoProfileV1'));if(p&&typeof p==='object')for(const k of Object.keys(profile))if(typeof p[k]===typeof profile[k])profile[k]=typeof p[k]==='number'?Math.max(0,Math.floor(p[k])):p[k];}catch{}
  function save(){try{localStorage.setItem('bigTwoProfileV1',JSON.stringify(profile));}catch{}}
  function progress(){const level=Math.floor(profile.xp/200)+1;$('level').textContent=`Level ${level} · ${level>=10?'Card Master':level>=5?'Strategist':level>=2?'Challenger':'Rookie'}`;$('xp').textContent=`${profile.xp} XP`;$('xpBar').value=profile.xp%200;$('stats').textContent=`${profile.wins} overwinningen · ${profile.games} rondes`;$('badges').textContent=[profile.wins?'🏆 Eerste winst':'',profile.best>=3?'🔥 3 op rij':'',profile.expert?'👑 Expert':''].filter(Boolean).join('  ');}
  function card(c,interactive=false){const el=document.createElement(interactive?'button':'div');el.className='card'+([0,2].includes(B.suit(c))?' red':'')+(selected.has(c)&&interactive?' selected':'');el.innerHTML=`<span class="corner">${B.ranks[B.rank(c)]}${B.suits[B.suit(c)]}</span><span class="pip">${B.suits[B.suit(c)]}</span><span class="bottomCorner">${B.ranks[B.rank(c)]}${B.suits[B.suit(c)]}</span>`;if(interactive){el.type='button';el.setAttribute('aria-label',`${B.ranks[B.rank(c)]} ${['ruiten','klaveren','harten','schoppen'][B.suit(c)]}`);el.setAttribute('aria-pressed',selected.has(c));el.disabled=state.turn!==0||state.winner!==null;el.onclick=()=>{selected.has(c)?selected.delete(c):selected.add(c);renderHand();};}return el;}
  function message(s){$('status').textContent=s;}
  function log(s){history.unshift(s);history=history.slice(0,12);$('history').replaceChildren(...history.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}
  function renderHand(){if(!state)return;const focus=document.activeElement?.getAttribute('aria-label');const hand=bySuit?[...state.hands[0]].sort((a,b)=>B.suit(a)-B.suit(b)||a-b):state.hands[0];$('hand').replaceChildren(...hand.map(c=>card(c,true)));if(focus){const same=[...$('hand').children].find(e=>e.getAttribute('aria-label')===focus);same?.focus({preventScroll:true});}const mine=state.turn===0&&state.winner===null;const c=[...selected],m=B.classify(c),valid=mine&&B.beats(m,state.table)&&(!state.opening||c.includes(0));$('play').disabled=!valid;$('pass').disabled=!mine||!state.table;$('hint').disabled=!mine;$('selection').textContent=c.length?(m?m.name:'Ongeldige combinatie')+(!valid&&m?' · kan nu niet gespeeld worden':''):'Kies een kaart of combinatie';$('yourCount').textContent=`${hand.length} kaarten`;}
  function render(){if(!state)return;for(let i=1;i<4;i++){const el=$('opponent'+i);el.classList.toggle('active',state.turn===i&&state.winner===null);el.innerHTML=`<strong>${avatars[i]} ${names[i]}</strong><div class="backs" aria-hidden="true">▧▧▧▧▧</div><small>${state.hands[i].length} kaarten</small>`;}$('tableCards').replaceChildren(...(state.table?state.table.cards.map(c=>card(c)):[]));$('tableLabel').textContent=state.table?`${names[state.last].toUpperCase()} · ${state.table.name.toUpperCase()}`:state.opening?'OPEN MET RUITEN 3':'NIEUWE TAFEL';document.querySelector('.you').classList.toggle('active',state.turn===0&&state.winner===null);renderHand();}
  function tone(win=false){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=win?660:330;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.15);}catch{}}
  function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<36;i++){const p=document.createElement('i');p.className='confetti';p.style.left=Math.random()*100+'vw';p.style.background=['#d6ee91','#eeaa91','#86cddd'][i%3];p.style.animationDelay=Math.random()*.7+'s';document.body.append(p);setTimeout(()=>p.remove(),3200);}}
  function finish(){if(recorded)return;recorded=true;const win=state.winner===0;profile.games++;profile.xp+=win?125:25;if(win){profile.wins++;profile.streak++;profile.best=Math.max(profile.best,profile.streak);if(roundLevel==='hard')profile.expert=true;}else profile.streak=0;save();progress();message(`${names[state.winner]} wint de ronde!`);$('resultTag').textContent=win?'TAFEL GEWONNEN':'VOLGENDE RONDE, NIEUWE KANS';$('resultTitle').textContent=win?'Big win! 🏆':`${names[state.winner]} wint`;$('resultText').textContent=win?'+125 XP · Je hebt al je kaarten uitgespeeld.':`+25 XP · Je had nog ${state.hands[0].length} kaarten. Probeer het opnieuw!`;$('result').showModal();if(win)celebrate();tone(win);}
  function advance(){render();if(state.winner!==null){finish();return;}if(state.turn===0){message(state.opening?'Jij begint. Speel een combinatie met ♦3.':state.table?'Jouw beurt. Speel hoger of pas.':'Jij hebt de controle. Kies een nieuwe combinatie.');return;}message(`${names[state.turn]} denkt na…`);timer=setTimeout(()=>{timer=null;const actor=state.turn,m=B.choose(state.hands[actor],state.table,state.opening,roundLevel);if(m){B.play(state,m.cards);log(`${names[actor]} speelt ${m.name.toLowerCase()}: ${m.cards.map(c=>B.ranks[B.rank(c)]+B.suits[B.suit(c)]).join(' ')}`);tone();}else{B.pass(state);log(`${names[actor]} past.`);}advance();},750);}
  function start(){clearTimeout(timer);if($('result').open)$('result').close();roundLevel=$('difficulty').value;state=B.create();selected.clear();recorded=false;history=[];log(`Nieuwe ronde · ${$('difficulty').selectedOptions[0].textContent}`);advance();}
  $('start').onclick=()=>{if(state&&state.winner===null){if(!confirm('Deze ronde stoppen en opnieuw delen?'))return;}start();};$('again').onclick=start;$('closeResult').onclick=()=>$('result').close();$('play').onclick=()=>{if(!state||state.turn!==0)return;try{const m=B.play(state,[...selected]);log(`Jij speelt ${m.name.toLowerCase()}.`);selected.clear();tone();advance();}catch(e){message(e.message);}};$('pass').onclick=()=>{if(!state||state.turn!==0)return;try{B.pass(state);selected.clear();log('Jij past.');advance();}catch(e){message(e.message);}};$('hint').onclick=()=>{if(!state||state.turn!==0)return;const m=B.choose(state.hands[0],state.table,state.opening,'hard');selected=new Set(m?.cards||[]);renderHand();message(m?`Tip: speel ${m.name.toLowerCase()}. Je mag ook zelf kiezen.`:'Je kunt deze combinatie niet verslaan. Pas deze beurt.');};$('sort').onclick=()=>{bySuit=!bySuit;$('sort').textContent=bySuit?'Sorteer op waarde':'Sorteer op soort';renderHand();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Geluid aan':'Geluid uit';$('sound').setAttribute('aria-pressed',sound);tone();};$('rulesButton').onclick=()=>$('rules').showModal();$('closeRules').onclick=()=>$('rules').close();for(const id of ['play','pass','hint'])$(id).disabled=true;progress();
})();
